### ISSUE TITLE
Font family not working together with font size

### ISSUE THREAD

**Issue by Tlapi** [ckeditor/ckeditor5-font#12]
Using this plugin when I select both font-size and font family, it results to:

`<span class="text-huge" style="font-family:Bitter, Georgia, serif;">test</span>`

That is OK

But when CKeditor loads this, it removes `font-family` style.

However when you do not choose font size and load this, it works good:
`<span style="font-family:Bitter, Georgia, serif;">test</span>`

**Comment by Reinmar** [comment]
cc @jodator

**Comment by jodator** [comment]
Yes we are aware of this problem. However we need to fix this at engine level: https://github.com/ckeditor/ckeditor5-engine/issues/1348.

**Comment by jodator** [comment]
I'm closing this as https://github.com/ckeditor/ckeditor5-engine/issues/1348 is closed. The issue was fixed at the engine level:

![selection_025](https://user-images.githubusercontent.com/247363/37957319-ed83bc5e-31ad-11e8-8b38-957a2c92ee0b.png)

**Comment by jodator** [comment]
I've forgot to update the font definitions.

**Comment by jodator** [comment]
Ugh.. again sorry. I've just forgot to rebuild the decoupled editor build before testing it.

It works as supposed without touching the font conversion definitions.
