### ISSUE TITLE
Hi! Could Font Size Icon change to the real value?

### ISSUE THREAD

**Issue by wuguokai** [ckeditor/ckeditor5-font#23]
Now Font Size Icon is a svg 
![image](https://user-images.githubusercontent.com/30334643/49208771-9e1b6c80-f3f3-11e8-8042-34fe81019108.png)
I want to change it to the real value.like this:
![image](https://user-images.githubusercontent.com/30334643/49208827-cb681a80-f3f3-11e8-9f6a-3aa145bdf326.png)
How should I do it?
Thank you!

**Comment by jodator** [comment]
You need to create a [custom CKEditor 5 build](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/development/custom-builds.html) with a plugin which will create custom component.

Taken from [similar feature request](https://github.com/ckeditor/ckeditor5-font/issues/18):

```js
export class MyCustomFontSizeUI extends Plugin {
	init() {
		this.editor.ui.componentFactory.add( 'fontSizeDropdown', () => {
			const editor = this.editor;

			const command = editor.commands.get( 'fontSize' );

			// Use original fontSize button - we only changes its behavior.
			const dropdownView = editor.ui.componentFactory.create( 'fontSize' );

			// Show label on dropdown's button.
			dropdownView.buttonView.set( 'withText', true );

			// Disable icon on the button.
			dropdownView.buttonView.set( 'icon', false );

			// To hide the icon uncomment below.
			// dropdownView.buttonView.set( 'icon', false );

			// Bind dropdown's button label to fontSize value.
			dropdownView.buttonView.bind( 'label' ).to( command, 'value', value => {
				// If no value is set on the command show 'Default' text.
				// Use t() method to make that string translatable.
				return value ? value : '16'; // The Default size is '16'
			} );

			return dropdownView;
		} );
	}
}
```

In action:
![peek 2018-11-29 10-01](https://user-images.githubusercontent.com/247363/49210591-c4261a00-f3bd-11e8-8fb7-32c508d5ea1a.gif)

ps.: I'm closing this as a dup of #18.

**Comment by wuguokai** [comment]
Sorry! I'm so stupid. I have added the component, but throw the error:
![image](https://user-images.githubusercontent.com/30334643/49213609-a24d8700-f3ff-11e8-859a-1296689140b9.png)
1.add the component:
![image](https://user-images.githubusercontent.com/30334643/49213679-c610cd00-f3ff-11e8-8e5e-a3688bd1d89b.png)
2.import it and add the toolbar:
![image](https://user-images.githubusercontent.com/30334643/49213711-da54ca00-f3ff-11e8-8242-1136231a75e6.png)
![image](https://user-images.githubusercontent.com/30334643/49213728-e0e34180-f3ff-11e8-89f2-5a0e03b2ccdb.png)
3.build and use it.

**Comment by jodator** [comment]
@wuguokai You also need to add it to the plugin lists (:

```js
// Plugins to include in the build.
DecoupledEditor.builtinPlugins = [
	// ...    
	TableToolbar,
	MyCustomFontSizeUI
];
```

**Comment by wuguokai** [comment]
Thanks very much ! You are right , add it to the plugin lists and it run success! 👍
