### ISSUE TITLE
Font color/background remains in the view after removing it from a text with multiple attributes

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-font#30]
## Steps to reproduce
1. Open the font color sample.
1. Put the caret in the first paragraph.
1. Select whole text.
1. Add font color, font background, bold and italic.
1. Put the caret in the middle of the sentence.
1. Press <kbd>Enter</kbd>.
1. Select divided parts.
1. Remove the font color/background.

## Current result
The font color/background has been removed from the model but it still exists in the view.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/55240806-095a3b80-523a-11e9-9277-14ad4ec23f89.gif)

**Comment by oleq** [comment]
Any errors? This could be the same as https://github.com/ckeditor/ckeditor5-remove-format/pull/1#pullrequestreview-220515609.

**Comment by Mgsy** [comment]
>Any errors? This could be the same as ckeditor/ckeditor5-remove-format#1 (review).

Nope, no errors.

**Comment by oleq** [comment]
Something's wrong with the conversion. Attributes are removed correctly in the model but the view does not reflect that.

cc @msamsel

**Comment by msamsel** [comment]
I talked with @scofalik to help me with debugging it. He suspects that issue might be somewhere in `viewWriter`.

**Comment by msamsel** [comment]
It's an upstream issue:
https://github.com/ckeditor/ckeditor5-engine/issues/1716
