### ISSUE TITLE
Font Size & Font Family UI/UX

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-font#4]
To not duplicate lengthy talks from Highlight feature I'd like to ask you guys how the UI/UX for those features should like.

As a reminder both features will be uses as "non-semantic" features mostly in some conjuction with PasteFromWord (in the future) to individually style parts of text with different font size or font family.

Font sizes might be configured either as [named presets or px values](https://github.com/ckeditor/ckeditor5/issues/638#issuecomment-347271402). 

---

Previous thoughts on this:
> We need to think how these two features (font family and font size) will be presented in the toolbar. The "Normal" label makes no sense for the dropdown's main button (imagine two "Normal" buttons next to each other ;)). So it seems that we need some icons for both of them. But then, do we also want to show the current size/family?

> Also, in terms of UI, we may consider a single dropdown for both these features but I'd rather go with separate ones to not overcomplicate the initial implementation. Especially, if we'll choose to have just normal, small icons in those dropdown's main buttons.

> Completely agree, remember that we have also heading, so it's equal to 3 dropdowns in a row, it's too much for the toolbar.

> >    But then, do we also want to show the current size/family?

> IMHO displaying enabled type like in headings it's not necessary.

> We just need to properly present font-size and font-family icons.

**Comment by jodator** [comment]
As starters we go with buttons for both Font Family and Font Size.

The dropdown for font family will represent rendered font.

The dropdown for font size will represent configured values either as numbers ( for px values) either as texts (for named presets).

**Comment by oleq** [comment]
Added the icons in 2bc0718. To be continued in https://github.com/ckeditor/ckeditor5/issues/645.

![image](https://user-images.githubusercontent.com/1099479/34298575-c2f4f59a-e71e-11e7-8a53-7b2e0196b069.png)
