### ISSUE TITLE
Refine document colors docs

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5-font#49]
In #28 (PR #39) we introduced document colors section to the font color dropdowns. It got a solid amount of API docs and and handful docs in feature section, but it could use further refinement / review.

**Comment by mlewand** [comment]
Please @Reinmar take a look at it before we proceed with it.

The subject documentation of this issue can be found in `http://<yourHost>/ckeditor5/ckeditor5/build/docs/ckeditor5/latest/features/font.html#documents-colors` (change `<yourHost>` here).

Most relevant sections are:
* Documents colors
* Changing the geometry of the color grid

**Comment by Reinmar** [comment]
Tech review done: https://github.com/ckeditor/ckeditor5-font/commit/dc2d679fe89b28dead88ef754ee974d6c02aaad0.

Leaving the proofreading to @AnnaTomanek (separate ticket).
