### ISSUE TITLE
Newest npm and node versions not supported

### ISSUE THREAD

**Issue by henrijeret** [ckeditor/ckeditor5-font#50]
Having troubles with using ckeditor5-font with newer node and npm.

"Unsupported engine for @ckeditor/ckeditor5-font@11.1.1: wanted: {"node":">=8.0.0","npm":">=5.7.1"} (current: {"node":"10.13.0","npm":"6.9.1-next.0"})"

Is there a workaround or could I test the editor with the new node and update it?

**Comment by Reinmar** [comment]
WAT... 😮 That doesn't seem to make any sense. We use `>=` version specifiers which mean that it should work with any newer version. But it doesn't because it filters out `-next.0`:

![image](https://user-images.githubusercontent.com/156149/60175256-47ec9b80-9813-11e9-94af-bb2b788e3c7d.png)

This is weird. What kind of version specifier we should be using then? 😬

**Comment by jodator** [comment]
I think that it makes perfect sense that we do not allow pre-releases: https://semver.org/#spec-item-9 and only stable versions.

**Comment by jodator** [comment]
ps.: from [npm repo](https://github.com/npm/cli/releases):

![image](https://user-images.githubusercontent.com/247363/60175644-6acb7f80-9814-11e9-8853-b1ee48e9a7c3.png)

**Comment by Reinmar** [comment]
> I think that it makes perfect sense that we do not allow pre-releases: https://semver.org/#spec-item-9 but only stable versions.

Why? If we're talking about your package deps, then I agree because releasing a new version of a dependency isn't in your control. But here we're talking about developer's environment and it's completely under their control.

**Comment by Reinmar** [comment]
Hoping to learn the answer in https://twitter.com/reinmarpl/status/1143840048389005312.

**Comment by wwalc** [comment]
@henrijeret Out of curiosity, what's your setting in `.npmrc`? Do you have perhaps `engine-strict=true` set there?

**Comment by henrijeret** [comment]
> @henrijeret Out of curiosity, what's your setting in `.npmrc`? Do you have perhaps `engine-strict=true` set there?

You are right and this was causing this error. Removed the line (wasn't there with any purpose) and everything installed.

A case of inexperience. Thank you, @wwalc
